Fix asan failed for memroy leak
cyfitech/cris-core pull request #115
Opened 2022-12-07 04:16 UTC by yanglu1225

- https://github.com/cyfitech/cris-xchg/issues/400

队列中new出来的job没有释放，导致了内存泄漏

2022-12-07 04:18 UTC, yanglu1225 commented
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //nodes/trade_agent/mocking_agent:mocking_message_node_test
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MockingMessageNode
[ RUN      ] MockingMessageNode.Merge
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20221206 13:40:57.985741    12 job_runner.cc:200] JobRunner: JobRunner at 0x607000001e50 initialized with 1 worker(s). 0 of them always stay active, others go to sleep if stay idle for more than 0 ms.
I20221206 13:40:57.988095    12 node.cc:19] CRNode: Binding node "cris::nodes::MockingMessageNode"(at 0x7ffd274796a0) to runner at 0x607000001e50
I20221206 13:40:57.988170    12 node.cc:14] CRNode: Node "noname"(at 0x7ffd274797c8) binds with no runner.
I20221206 13:40:57.993841    12 job_runner.cc:200] JobRunner: JobRunner at 0x607000002080 initialized with 1 worker(s). 0 of them always stay active, others go to sleep if stay idle for more than 0 ms.
I20221206 13:40:57.995184    12 node.cc:19] CRNode: Binding node "noname"(at 0x7ffd27479920) to runner at 0x607000002080
I20221206 13:40:57.996515    12 node.cc:14] CRNode: Node "noname"(at 0x7ffd27479a10) binds with no runner.
[       OK ] MockingMessageNode.Merge (122 ms)
[----------] 1 test from MockingMessageNode (122 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (122 ms total)
[  PASSED  ] 1 test.

=================================================================
==12==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x3b4a2d in operator new(unsigned long) (/home/ly/.cache/bazel/_bazel_ly/925a5f9b41a361ffdb43574a6e9ec3a6/execroot/cris-xchg/bazel-out/k8-opt/bin/nodes/trade_agent/mocking_agent/mocking_message_node_test+0x3b4a2d)
    #1 0x3ff0a8 in cris::core::JobRunnerStrand::AddJob(std::function<void (std::shared_ptr<cris::core::JobAliveToken>&&)>&&) /proc/self/cwd/external/cris-core/src/sched/job_runner.cc:125:24
    #2 0x402750 in cris::core::JobRunner::AddJob(std::function<void (std::shared_ptr<cris::core::JobAliveToken>&&)>&&, std::shared_ptr<cris::core::JobRunnerStrand>) /proc/self/cwd/external/cris-core/src/sched/job_runner.cc:251:29
    #3 0x3f4cd6 in bool cris::core::CRNode::AddJobToRunner<cris::core::CRNode::AddMessageToRunner(std::shared_ptr<cris::core::CRMessageBase> const&)::$_0>(cris::core::CRNode::AddMessageToRunner(std::shared_ptr<cris::core::CRMessageBase> const&)::$_0&&, std::shared_ptr<cris::core::JobRunnerStrand>) /proc/self/cwd/bazel-out/k8-opt/bin/external/cris-core/_virtual_includes/msg/cris/core/msg/node.h:117:24
    #4 0x3f4cd6 in cris::core::CRNode::AddMessageToRunner(std::shared_ptr<cris::core::CRMessageBase> const&) /proc/self/cwd/external/cris-core/src/msg/node.cc:35:16
    #5 0x3fb7da in cris::core::(anonymous namespace)::SubscriptionMap::Dispatch(std::shared_ptr<cris::core::CRMessageBase> const&) /proc/self/cwd/external/cris-core/src/msg/message.cc:83:36
    #6 0x3fb7da in cris::core::CRMessageBase::Dispatch(std::shared_ptr<cris::core::CRMessageBase> const&) /proc/self/cwd/external/cris-core/src/msg/message.cc:108:43
    #7 0x3e5bf4 in cris::nodes::MockingMessageNode::TryToSendMessage() /proc/self/cwd/nodes/trade_agent/mocking_agent/mocking_message_node.cc:105:20
    #8 0x3ecc9d in cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3::operator()(std::shared_ptr<cris::nodes::MockingTradeAgent::MockEnd> const&) const /proc/self/cwd/nodes/trade_agent/mocking_agent/mocking_message_node.cc:94:13
    #9 0x3ecc9d in void cris::core::CRNode::Subscribe<cris::nodes::MockingTradeAgent::MockEnd, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3>(unsigned long, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3&&, std::shared_ptr<cris::core::JobRunnerStrand>)::'lambda'(std::shared_ptr<cris::core::CRMessageBase> const&, std::shared_ptr<cris::core::JobAliveToken>&&)::operator()(std::shared_ptr<cris::core::CRMessageBase> const&, std::shared_ptr<cris::core::JobAliveToken>&&) const /proc/self/cwd/bazel-out/k8-opt/bin/external/cris-core/_virtual_includes/msg/cris/core/msg/node.h:140:13
    #10 0x3ecc9d in cris::nodes::MockingTradeAgent::MockEnd std::__invoke_impl<void, void cris::core::CRNode::Subscribe<cris::nodes::MockingTradeAgent::MockEnd, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3>(unsigned long, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3&&, std::shared_ptr<cris::core::JobRunnerStrand>)::'lambda'(std::shared_ptr<cris::core::CRMessageBase> const&, std::shared_ptr<cris::core::JobAliveToken>&&)&, std::shared_ptr<cris::core::CRMessageBase> const&, std::shared_ptr<cris::core::JobAliveToken> >(std::__invoke_other, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3&&, void cris::core::CRNode::Subscribe<cris::nodes::MockingTradeAgent::MockEnd, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3>(unsigned long, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3&&, std::shared_ptr<cris::core::JobRunnerStrand>)::'lambda'(std::shared_ptr<cris::core::CRMessageBase> const&, std::shared_ptr<cris::core::JobAliveToken>&&)&...) /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/invoke.h:60:14
    #11 0x3ecc9d in std::enable_if<is_invocable_r_v<cris::nodes::MockingTradeAgent::MockEnd, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3, void cris::core::CRNode::Subscribe<cris::nodes::MockingTradeAgent::MockEnd, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3>(unsigned long, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3&&, std::shared_ptr<cris::core::JobRunnerStrand>)::'lambda'(std::shared_ptr<cris::core::CRMessageBase> const&, std::shared_ptr<cris::core::JobAliveToken>&&)&...>, cris::nodes::MockingTradeAgent::MockEnd>::type std::__invoke_r<void, void cris::core::CRNode::Subscribe<cris::nodes::MockingTradeAgent::MockEnd, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3>(unsigned long, cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3&&, std::shared_ptr<cris::core::JobRunnerStrand>)::'lambda'(std::shared_ptr<cris::core::CRMessageBase> const&, std::shared_ptr<cris::core::JobAliveToken>&&)&, std::shared_ptr<cris::core::CRMessageBase> const&, std::shared_ptr<cris::core::JobAliveToken> >(cris::nodes::MockingMessageNode::MockingMessageNode(cris::libs::ExchangeID, cris::message::TradeSymbol, std::shared_ptr<cris::core::JobRunner>, unsigned long)::$_3&& [...]

2022-12-07 07:10 UTC, chenhao94 commented
@yanglu1225 不要把带有内部信息的log随意贴到public仓库

2022-12-07 07:12 UTC, chenhao94 commented on src/sched/job_runner.cc
> +        pending_jobs_.pop(data);
- consume all？
- 直接扔给一个uniqueptr，不必手动delete。你可以参考runner里job queue的析构方式

2022-12-07 07:13 UTC, yanglu1225 commented
> 不要把带有内部信息的log随意贴到public仓库

ok

2022-12-07 07:13 UTC, chenhao94 commented on src/sched/job_runner.cc
> +        pending_jobs_.pop(data);
析构前先保证其他地方不会在析构中途从queue里拿job破坏正确性

2022-12-07 09:34 UTC, xkszltl commented
为什么在我们的测试中末尾会有job，是还没跑/没wait还是真漏了？如果是前者，那这里就有了一个cancel/kill的语义，有没有必要在API层面展示出来？包括如果没手动cancel的话还有job应该报错而非直接删了。

2022-12-07 13:30 UTC, yanglu1225 commented
> 为什么在我们的测试中末尾会有job，是还没跑/没wait还是真漏了？如果是前者，那这里就有了一个cancel/kill的语义，有没有必要在API层面展示出来？包括如果没手动cancel的话还有job应该报错而非直接删了。

刚看了test，写的也有点问题，就是都缓存在最后，发了mockend之后，才合并再发出去。所以就都等到了程序快结束的时候才发消息。

2022-12-07 19:46 UTC, chenhao94 requested changes

2022-12-07 19:49 UTC, chenhao94 commented on src/sched/job_runner.cc
> +    if (finished_) [[unlikely]] {
一个可能的思路是，你析构时要整体block住所有未来的job，然后你证明析构开始之后，不再会有新的job进入runner，之后再清空队列，这样就能保持原来部分证明不变（如果你没有修改原来的部分）

2022-12-08 03:12 UTC, chenhao94 commented on src/sched/job_runner.cc
> +    std::lock_guard<std::mutex> lck(pending_jobs_mutex_);
整个锁住是正确，但很慢的行为。如果你仔细看一下这些代码以及证明，我们所有的复杂结构都是为了避免这样做

2022-12-08 03:12 UTC, chenhao94 commented on src/sched/job_runner.cc
>      // Decision(D/d). It is protected by lock and it decides whether Push is needed.
这个阶段是锁保护的，你析构可以利用这点。我没有仔细想详细该如何做，但这里应该是有办法挡住后续job的。

但还有一个问题，既然你需要清除所有job，那你析构完成前是不是除了挡住后面的job，也应该先等目前的job结束？

2022-12-08 03:21 UTC, yanglu1225 commented on src/sched/job_runner.cc
> +        LOG(ERROR) << __func__ << ": JobRunnerStrand have destoryed.";
我觉得应该要做成等所有任务完成了再析构比较好。

2022-12-08 03:24 UTC, yanglu1225 commented on src/sched/job_runner.cc
>      // Decision(D/d). It is protected by lock and it decides whether Push is needed.
我觉得要等待所有正在跑的job结束，不让新的job进来，最后析构

2022-12-08 03:41 UTC, chenhao94 commented on src/sched/job_runner.cc
>      // Decision(D/d). It is protected by lock and it decides whether Push is needed.
可是你最后好像没有什么地方等，所以两个问题

- 不等会怎么样
- 要怎么等

2022-12-08 03:42 UTC, yanglu1225 commented on src/sched/job_runner.cc
>      // Decision(D/d). It is protected by lock and it decides whether Push is needed.
我再看看，怎么写

2022-12-08 03:43 UTC, chenhao94 commented on src/sched/job_runner.cc
> +        LOG(ERROR) << __func__ << ": JobRunnerStrand have destoryed.";
所以说，你认为在还有任务没结束的情况下析构是一个**错误**。那有什么方便的方法可以等待任务结束再析构吗，等待途中有新的任务进来该怎么处理呢？继续等？报错？忽略？

2022-12-13 02:52 UTC, yanglu1225 commented
修改了，在析构的时候，会将剩余的job加入到队列中执行

2022-12-13 05:34 UTC, chenhao94 commented on src/sched/job_runner.cc
> +            runner->AddJob(std::move(*next));
这是错的啊....这样不就变成析构之后job之间没有序列化了

2022-12-13 18:39 UTC, chenhao94 commented on src/sched/job_runner.cc
> +            runner->AddJob(std::move(*next));
注意strand的功能是，对于加进来的job，后加的开始时间不会早于先加的结束时间。不管你怎么处理，这个条件必须要满足，不然就是在改变strand的含义。如果你要析构strand，对于剩下的job你可以有以下几种可能的处理方式：
- 丢弃还未开始的job。这样不会违反有序性。这种情况可能需要在log里（error/warning？）说明你丢弃了一部分job
- 等待所有job结束。你仍然要保持有序，所以这个等待时间可能会很长，而且此时有新的job进来你是不是也要继续等待？继续等待的话可能你无法完成析构，因为strand内的job可以继续往strand里加入新的job。
- 忽略，直接析构，让caller自行保证没有资源泄漏。这个可能会造成各种报错，但好处是简单，并且caller可以手动控制哪些job必须要完成。

不管你选择哪种处理方式，都 1.不能造成性能损失；2.不能改变strand的含义。

2022-12-14 05:56 UTC, yanglu1225 commented on src/sched/job_runner.cc
> +            runner->AddJob(std::move(*next));
我可能还没看懂这块的代码

2022-12-15 06:44 UTC, yanglu1225 commented on src/sched/job_runner.cc
> +            runner->AddJob(std::move(*next));
问个问题：

我看到保证顺序执行的逻辑是，依靠上一个job完毕后，在~JobAliveToken()里面，push下一个job去执行？
这样可以保证pending_jobs_里面的job可以依次执行。
但是如果想中断，或者拿到整个的状态就很困难。

是这样吗？

2022-12-15 07:27 UTC, chenhao94 commented on src/sched/job_runner.cc
> +            runner->AddJob(std::move(*next));
对，但我不明白你说的是什么样的整个状态。

想中断的话很容易，你让push那一步不继续加新job就可以中断了

2022-12-15 07:33 UTC, yanglu1225 commented on src/sched/job_runner.cc
> +            runner->AddJob(std::move(*next));
但是中断了的话，不是会出现内存泄漏吗？

在析构函数里面，就难以知道每个job的状态，wait它结束。

2022-12-15 19:30 UTC, chenhao94 commented on src/sched/job_runner.cc
> +            runner->AddJob(std::move(*next));
中断不一定意味着内存泄漏，你可以自行回收这些job对象，而不必运行他们。

2022-12-23 04:06 UTC, chenhao94 requested changes

2022-12-23 04:06 UTC, chenhao94 commented on src/sched/job_runner.cc
> +    if (finished_.load()) [[unlikely]] {
在这条检查之后，push之前析构，不还是错了吗？

2022-12-23 04:06 UTC, chenhao94 commented on src/sched/job_runner.cc
> +    if (finished_.load()) [[unlikely]] {
这条检查没意义，因为你在pushifneeded里面反正要做，中间没有其他出口

2023-01-05 03:49 UTC, chenhao94 requested changes

2023-01-05 03:49 UTC, chenhao94 commented on src/sched/job_runner.cc
> +        cv.wait_for(lock, std::chrono::milliseconds(100));
这不就是sleep 100ms?

2023-01-05 03:49 UTC, chenhao94 commented on src/sched/job_runner.cc
> +    pending_pushing_.store(pending_pushing);
你在试图把原子变量当锁用？这是不可能的，除非你真的实现一个锁

2023-01-05 03:49 UTC, chenhao94 commented on src/sched/job_runner.cc
> +    pending_pushing_.store(pending_pushing);
这是一个多线程计算里很基础的被证明不可解的问题：你无法只用读写操作实现consensus

这里的反例：
- 开始析构，pending没设置
- 然后你就绕过了你所有的pending flag逻辑

如果你还是想用原子变量读写来模拟锁的话，永远会有反例，因为这是**不可解问题**。这也是为什么我们写这种东西需要**数学证明**

2023-01-05 03:49 UTC, chenhao94 commented on src/sched/job_runner.cc
> +    pending_pushing_.store(pending_pushing);
可能的方法是，你用一个flag在析构时挡住新的job，这个flag不会重置所以不需要模拟锁。但你要想好你想要的行为是什么，并给出**证明**

2023-01-05 19:53 UTC, xkszltl commented on src/sched/job_runner.cc
> +    pending_pushing_.store(pending_pushing);
@chenhao94 注意一下consensus这个词可能很多人不认识

2023-01-30 03:43 UTC, closed without merging