Recorder snapshot feature with single time interval
cyfitech/cris-core pull request #116
Opened 2022-12-08 10:43 UTC by YuzhouGuo

Associate with the feature
- https://github.com/cyfitech/cris-core/issues/97

Depends on the PR
- https://github.com/cyfitech/cris-core/pull/106
- https://github.com/cyfitech/cris-core/pull/101

Feature description:
- Changed the `MessageRecorder` constructor and provided a struct for interval specification and record path (see first PR dependency), a merge request in `cris` repo is needed as well.
- If the user did provide time intervals, then a data snapshot will be generated periodically.
- Support only single time intervals, multi-interval implementation will be supported in the future.

2022-12-08 10:53 UTC, YuzhouGuo commented
@chenhao94 `tsan` failed and I did call `runner->Stop()`.
From the direct error message, looks like it's something to do with the `RecordFile` vector. 
I tried to wait in the destructor for the `snapshot_pause_flag_` to become true to continue so that the `cv` and `mutex` won't conflict but it didn't work, thanks for the help.

2022-12-09 10:56 UTC, YuzhouGuo commented on tests/snapshot_test.cc
> +        std::this_thread::sleep_for(kSleepBetweenMessages);
Looks like something's wrong here with the sleep method causing the `tsan` failure, the `recorder` seems to be fine

2022-12-12 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> -#include <filesystem>
为什么要删掉？你有用过相关的函数吧

2022-12-12 04:40 UTC, chenhao94 commented on tests/BUILD
> +        ":job_runner_tsan_suppressions",
不要用jobrunner的，这测试自己有需要就自己写一个。不同测试可能需要suppress不同的东西，这不一定是可以共用的

2022-12-12 04:40 UTC, chenhao94 commented on tests/snapshot_test.cc
> +    TestSnapshotContent();
定义函数有什么原因？这些可能复用吗？

2022-12-12 04:40 UTC, chenhao94 commented on tests/snapshot_test.cc
> +    RecorderConfig GetTestConfig() const;
直接写在test里是不是更清楚？

2022-12-12 04:40 UTC, chenhao94 commented on tests/snapshot_test.cc
> +    static constexpr channel_subid_t kTestIntChannelSubId  = 11;
不知道这里有多少是适合放在test class里的？有些东西直接放test里面是不是更清楚？我觉得这个test fixture class只是为了回收创建的这些目录？

2022-12-12 04:40 UTC, chenhao94 commented on tests/snapshot_test.cc
> +        .interval_sec_ = kSleepBetweenMessages,
- 难读，这里要跳好几层才知道你是一秒snapshot一次。再次强调，测试的代码写法更加注重易读而不是少重复
- 一秒一条信息+一秒一个snapshot，听起来非常flaky，稍微有点调度上不准可能就会fail，而且也不好放宽条件。不如一秒一个snapshot，但一秒10条/20条信息？
- 消息之间不要用常数的等待时间，同样会有积分误差

2022-12-12 04:40 UTC, chenhao94 commented on tests/snapshot_test.cc
> +        snapshot_made_map_[fmt::format("{:%Y%m%d-%H%M%S.%Z}", std::chrono::system_clock::now())] = i;
这个map是做什么的？如果你要验证数据正确，是不是给一个数据生成规则，去验证录下来的数据是不是符合规则就好了

2022-12-12 04:40 UTC, chenhao94 commented on tests/snapshot_test.cc
> +    runner->Stop();
如果不拆test，这里也没必要stop一下了，继续用这个runner就好

2022-12-12 05:58 UTC, YuzhouGuo commented on tests/snapshot_test.cc
> +        snapshot_made_map_[fmt::format("{:%Y%m%d-%H%M%S.%Z}", std::chrono::system_clock::now())] = i;
我现在的思路大概是这样：
- 首先 `recorder` 里面的snapshot data 路径名称是精确到秒的
```
std::string MessageRecorder::SnapshotDirNameGenerator() {
    return fmt::format("{:%Y%m%d-%H%M%S.%Z}", std::chrono::system_clock::now());
}
```
- 所以 `snapshot_made_map_`的key是同样的记录方法，这样可以保证找到同一个路径下的数据（recorder的snapshot相关方法因为是在lambda里面做的，很难直接return路径，不然的话unit test可以直接存下来）
-  `snapshot_made_map_`的value是 made snapshot那一瞬间 `i` 的值
- 之后验证某个dir下的数据的时候可以参考map里i的值，比如第0秒的snapshot 就是0到0， 第2秒的数据是01，第3秒的是012

2022-12-12 06:12 UTC, chenhao94 commented on tests/snapshot_test.cc
> +        snapshot_made_map_[fmt::format("{:%Y%m%d-%H%M%S.%Z}", std::chrono::system_clock::now())] = i;
那这就更有问题了。单元测试测的是功能，是接口是不是实现了预想中的功能。snapshot的路径格式是implementation，接口里没有规定过，你在这里直接去预设snapshot的路径格式相当于让测试混入了implementation detail，今后detail改变，或者有另一个版本的implementation，你的测试都会有问题。测试里一般都想要避免这种情况

2022-12-12 06:14 UTC, chenhao94 commented on tests/snapshot_test.cc
> +        snapshot_made_map_[fmt::format("{:%Y%m%d-%H%M%S.%Z}", std::chrono::system_clock::now())] = i;
所以是不是可以为了测试，添加一个“目前可用的snapshot列表”这样的接口？这样你就不需要在外面依赖内部的snapshot路径格式。

2022-12-13 05:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> -#include <filesystem>
那是因为header的接口用到了，这没错，但是cc里面自己在实现里用到了，也要加，因为如果h改变，不再用到filesystem了，这里就错了。当然如果你只是在h定义的接口里用到了那确实可以不加

@xkszltl 你有没有什么成文的include的规则？

2022-12-13 06:00 UTC, chenhao94 commented on tests/snapshot_test.cc
> +        auto previous_int = std::make_shared<std::atomic<int>>(0);
为什么要原子变量？你订阅时不允许并行不就好了。而且你这里不能有并行，因为你写的检查是不支持乱序的

2022-12-13 06:03 UTC, chenhao94 commented on tests/snapshot_test.cc
> +        EXPECT_EQ(previous_int->load(), snapshot_point_list[dir_entry_counter]);
这应该放松成一个取值区间减少flakiness

2022-12-13 06:07 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> -#include <filesystem>
就这个情况而言的话，头文件里确实是用到了

2022-12-13 06:10 UTC, YuzhouGuo commented on tests/snapshot_test.cc
> +    std::sort(snapshot_path_list.begin(), snapshot_path_list.end());
确实...主要是想要用本地变量做存储和排序，这样就不需要 `recorder`在多线程中return给我东西了，我看看怎么弄个时间顺序的compare

2022-12-13 06:17 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> -#include <filesystem>
举个例子，你用了create_directories，那这东西不管你头文件里有没有用，或者以后哪天觉得头文件直接用string更好不用fs了，你这儿都是得create的对吧

2022-12-13 06:18 UTC, chenhao94 commented on tests/snapshot_test.cc
> +    std::sort(snapshot_path_list.begin(), snapshot_path_list.end());
你这里不用弄也没法弄，你让recorder给你的list自己保证有序就行

2022-12-13 06:20 UTC, chenhao94 commented on tests/snapshot_test.cc
> +    std::sort(snapshot_path_list.begin(), snapshot_path_list.end());
直接按时间也不一定对，因为完全可能是早录的snapshot修改时间更新，因为读leveldb也会修改东西。

2022-12-13 06:34 UTC, YuzhouGuo commented on tests/snapshot_test.cc
> +    std::sort(snapshot_path_list.begin(), snapshot_path_list.end());
好，我直接在`recorder`里面返回一个不被修改的list，按创建时间排序

2022-12-13 08:21 UTC, YuzhouGuo commented on tests/snapshot_test.cc
> +        auto previous_int = std::make_shared<std::atomic<int>>(0);
后来发现，我147行在订阅之外还有value的检查，还是需要原子变量的

2022-12-14 04:40 UTC, chenhao94 commented on tests/msg_recorder_test.cc
> +        .snapshot_intervals_ = {},
这个不用写，vector的默认构造就是空

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.h
> +    const std::deque<std::filesystem::path>& GetSnapshotPaths();
- 返回一个copy就行了
- vector？
- 返回的列表保证了顺序的话，你要解释是什么样的顺序，不然之后没人会知道

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +void MessageRecorder::SetSnapshotInterval(const RecorderConfig& recorder_config) {
你真的不需要这个函数（我可能是第三遍还是第四遍说这个了）
- intervals你原样存下就好
- 临时性的判断在构造函数里做
- 线程在构造列表里就可以开

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +void MessageRecorder::SnapshotWorkerStart() {
这不是start，这就是worker

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    static constexpr auto kEpselonMs   = std::chrono::milliseconds(100);
- Epsilon？
- 这和epsilon有什么关系，我只知道epsilon一般用来表示误差

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    auto                  wake_up_time = std::chrono::system_clock::now();
不要用system clock，应该用steady clock，这两个区别非常大，前者是真实世界时间（需要不断对表，慢，可能因为校正而回退，适合用在需要知道现实世界时间的场景），后者是机器时间（不能对应到真实时间，但快，速率稳定，单调递增，适合用来计时）

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +        if (std::chrono::system_clock::now() <= (wake_up_time + kEpselonMs)) {
steady clock

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    auto                  wake_up_time = std::chrono::system_clock::now();
如果你其他地方不小心用了system clock，记得改过来

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +}
你这实际上是MakeSnapshotAsync，函数返回的时候snapshot并不一定做完了。所以你上面的写法是错误的，有可能下一次snapshot开始了上一次还没结束，甚至造成snapshot任务堆积。比如你第5秒发出的snapshot任务，被推到第10秒才开始做，snapshot的其实是前10秒的消息

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +        if (std::chrono::system_clock::now() <= (wake_up_time + kEpselonMs)) {
为了防止snapshot任务占满strand，你是不是可以说，如果现在离下次wake time只剩不到50%的周期，就跳过一次（并LOG WARNING）。

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +        }
else log？

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    while (!snapshot_shutdown_flag_) {
data race：SnapshotWorkerEnd里写，但这里读的时候没有锁保护。这里不需要锁但需要是原子变量

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +void MessageRecorder::GenerateSnapshot() {
名字和MakeSnapshot同义，无法看出区别

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    std::unique_lock<std::mutex> lock(snapshot_mtx_);
有了strand保护为什么还要锁？

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    std::for_each(files_.begin(), files_.end(), [](auto& file) { file->CloseDB(); });
execution plan？是不是可以par_unseq？

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    std::filesystem::path interval_dir = record_dir_.parent_path() / std::string("Snapshot") / snapshot_config_.name_;
snapshots，小写，复数？

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    std::filesystem::create_directories(interval_dir);
用带ec的版本并检查ec？

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    std::filesystem::create_directories(snapshot_dir);
- 同上，你要保证存在这个目录。
- 有了这个为什么还要上面那个

2022-12-14 04:40 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    const auto options      = std::filesystem::copy_options::recursive | std::filesystem::copy_options::skip_symlinks;
为什么是skip不是copy

2022-12-14 05:29 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +    static constexpr auto kEpselonMs   = std::chrono::milliseconds(100);
嗯对呀，我的意思就是醒来之后判断一个误差的时间，如果超过这个时间才跳过（毕竟按照计算，醒来必然已经超过wake up time了）

2022-12-14 05:34 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +    static constexpr auto kEpselonMs   = std::chrono::milliseconds(100);
看到了下面的留言
> 如果现在离下次wake time只剩不到50%的周期，就跳过一次
如果这样写的话那确实不需要这个Epsilon

2022-12-14 05:46 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +void MessageRecorder::SnapshotWorkerStart() {
还有一个`SnapshotWorkerEnd`，我想着名字对仗呢

2022-12-14 06:21 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +void MessageRecorder::SetSnapshotInterval(const RecorderConfig& recorder_config) {
我本来想的是，如果没有指定interval那这个线程也不用开了（还是说这个判断也可以在构造列表里原地完成？）

2022-12-14 10:10 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +        auto previous_int = std::make_shared<std::atomic<int>>(0);
我还是换回了原子变量，因为在`Subscribe`之外也需要检查值，上个版本用普通变量也是加了锁的

2022-12-14 10:20 UTC, YuzhouGuo commented on tests/msg_recorder_test.cc
> +        .snapshot_intervals_ = {},
不行， 我本地没问题但是CI报错：
```
tests/msg_recorder_test.cc:88:5: error: missing initializer for member 'cris::core::RecorderConfig::snapshot_intervals_' [-Werror=missing-field-initializers]
   88 |     };
      |     ^
```
所以我最后还是保持这样了

2022-12-15 04:28 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    snapshot_shutdown_flag_.store(true);
没有锁保护的原子变量notify之后对方不一定能立即看到。于是会发生wait醒来检查flag还是false，之后却不再有新的notify了，于是死循环。

https://en.cppreference.com/w/cpp/thread/condition_variable

> Even if the shared variable is atomic, it must be modified while owning the mutex to correctly publish the modification to the waiting thread.

2022-12-15 04:28 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    std::unique_lock<std::mutex> lock(snapshot_mtx_);
那你应该没必要锁住全部？

2022-12-15 04:28 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +std::vector<std::filesystem::path> MessageRecorder::GetSnapshotPaths() {
以后多周期要怎么办？不如提前想好？

2022-12-15 04:28 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +        EXPECT_TRUE((previous_int->load() >= int(expect_value - 1)) && (previous_int->load() <= int(expect_value + 1)));
- 不要cast，直接用原类型
- 不要hardcode 1

2022-12-15 04:28 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +        dir_entry_counter++;
这不就是list size么

2022-12-15 04:29 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +std::vector<std::filesystem::path> MessageRecorder::GetSnapshotPaths() {
我本地多周期已经改成map了，直接搬过来也行

2022-12-15 04:50 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +            AddSnapshotJobAsync();
有个问题，我这儿之前是用mutex lock加cv wait的方式来等待的，可是现在`GenerateSnapshot`里面也有mutex（我已经把scope改成了只应用于关闭DB的两个循环前后），两个锁不能套着用。

我想的是这样，跟之前的版本差不多
```
void MessageRecorder::AddSnapshotJobAsync() {
    std::unique_lock<std::mutex> lock(snapshot_mtx_);
    AddJobToRunner(
        [this]() {
            GenerateSnapshot();
            snapshot_pause_flag_ = true;
            snapshot_cv_.notify_all();
        },
        record_strand_);
    snapshot_cv_.wait(lock, [this] { return snapshot_pause_flag_; });
}
```

2022-12-15 04:56 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +        EXPECT_TRUE((previous_int->load() >= int(expect_value - 1)) && (previous_int->load() <= int(expect_value + 1)));
size_t不能跟int直接比较吧，因为TestMessage类型是int我就用了int作为`previous_int`的类型，这样的话总有一个地方要cast
```
comparison of integers of different signs: 'std::__atomic_base<int>::__int_type' (aka 'int') and 'const std::size_t' (aka 'const unsigned long') [-Werror,-Wsign-compare]
```
`expect_value`道理上也应该是size_t没错

2022-12-15 05:16 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +        EXPECT_TRUE((previous_int->load() >= int(expect_value - 1)) && (previous_int->load() <= int(expect_value + 1)));
那你消息里也用无符号是不是就好了

2022-12-15 05:21 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +            AddSnapshotJobAsync();
- 你这样就不是async了，名字要符合含义。这种误导的还不如没写清楚的
- 如果你只是为了wait，为啥一开始要锁？

2022-12-15 05:25 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +        EXPECT_TRUE((previous_int->load() >= int(expect_value - 1)) && (previous_int->load() <= int(expect_value + 1)));
是的我已经全员size_t解决了，所以默默把问题删了..

2022-12-15 05:32 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +            AddSnapshotJobAsync();
没太明白...不锁如何cv wait

2022-12-15 05:37 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +            AddSnapshotJobAsync();
要锁，可是你可以wait之前锁啊，之前无关的操作不需要一起锁吧，并不是写一个函数里就得一起锁的。

2022-12-15 10:04 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +    std::filesystem::copy(record_dir_, snapshot_dir, options);
之后其他的脚本需要依赖结果的，我加了LOG

2022-12-16 05:49 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +#include <execution>
这里有一点小问题：LLVM的libc++目前没有实现这些并行算法，所以我们需要一个类似这样的东西
https://github.com/cyfitech/cris/tree/master/libs/stl_adapter

你可以以后再考虑有没有必要，这里要不就先不用parunseq，不然在只有libc++的平台上（比如Mac OS）上无法编译

2022-12-16 05:51 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +#include <execution>
嗯好呀，之前跟@zptan也讨论过这边parunseq多线程划不划算的问题，既然有这个问题就先不用了

2022-12-16 06:24 UTC, chenhao94 requested changes

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +void MessageRecorder::AddSnapshotJob() {
名字还是不准确

AddSnapshotJob听起来是你把job加入某个队列就做完了（所以是async），但你在这里等待了任务结束，所以这其实是做完了一个Snapshot。

我理解你的函数内容变动很大，但每次改变你都要注意原来的名字是不是还能正确表达它的意思

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +                snapshot_pause_flag_ = true;
- 什么叫pause flag，你没有用这个在暂停什么东西
- 这个flag只有这里用到了，为什么需要是成员变量

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +        std::unique_lock lock(snapshot_mtx_);
- 如果没用到unqiue_lock那些功能，std::lock_guard就够了，其他地方也是
- lock -> lck，避免和类型名冲突

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    snapshot_dirs.push_back(snapshot_dir);
锁保护...

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    snapshot_dirs.push_back(snapshot_dir);
你的锁保护的是哪些结构？

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    snapshot_dirs.push_back(snapshot_dir);
你中间到底能不能临时放开锁？有没有什么问题？为什么之前不能一直锁住？

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    snapshot_path_map_.clear();
为什么要clear？snapshot线程停了不等于snapshot没了吧

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.h
> +    const std::map<std::string, std::vector<std::filesystem::path>> GetSnapshotPaths();
- 返回值是const没意义，反而可能影响RVO
- 注释解释返回的是什么映射到什么。vector是保证顺序的你也要说清楚，因为你自己单元测试也用到了这条性质。这些东西一点都不显然，但你不写的话过几天就没人还会记得有这回事

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    for (const auto& [k, v] : snapshot_path_map_) {
不要直接说k v，它们都是有意义的，要写清楚（可能是`const auto& [interval_name, snapshot_path_list]`?）

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +        std::vector<std::filesystem::path> snapshot_reference_paths_(v.begin(), v.end());
局部变量不要带后缀下划线，这是成员变量的格式

2022-12-16 06:24 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +        result_map[k] = std::move(snapshot_reference_paths_);
nit: `result_map[k] = std::vector(snapshot_path_list.begin(), snapshot_path_list.end());`

2022-12-16 06:33 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +    snapshot_path_map_.clear();
没太理解，这个只是把成员变量清除了呀，没有call remove path之类的函数吧？

2022-12-16 06:35 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +    const auto kSkipThreshold = sleep_interval * 0.5;
那我转成milliseconds再计算？

2022-12-16 06:46 UTC, YuzhouGuo commented on src/msg_recorder/recorder.h
> +    const std::map<std::string, std::vector<std::filesystem::path>> GetSnapshotPaths();
好的，我把注释转移到头文件里面吧

2022-12-16 06:59 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    snapshot_path_map_.clear();
我的问题是你为什么要手动清除呢？线程停止了之后你还是可以自己留着snapshot的列表啊

2022-12-16 07:03 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +    snapshot_path_map_.clear();
哦哦听懂了

2022-12-16 20:09 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +        std::unique_lock lock(snapshot_mtx_);
> lock -> lck，避免和类型名冲突

其他地方还有好几处

2022-12-16 20:11 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +void MessageRecorder::AddSnapshotJob() {
这里是公开接口吧，那最好给个好读一点的名字，比如`{Make,Generate}Snapshot`。底下用来加job的部分就叫XXX Impl，表示这是内部实现用的，不能直接调？

2022-12-16 20:33 UTC, chenhao94 reviewed
基本上只剩下一些测试的问题了

2022-12-16 20:33 UTC, chenhao94 commented on src/msg_recorder/recorder.h
> +    // and snapshot paths within time interval being the value, in order of ascending directory construction time
能不能写短一点？比如

Mapping from interval names to snapshot lists. Snapshots are ordered from old to new in the lists.

2022-12-16 20:33 UTC, chenhao94 commented on src/msg_recorder/recorder.h
> +    void SnapshotWorkerEnd();
StopSnapshotWorker. 用动词可以清楚表示这是一个动作，而不是结束时的callback

2022-12-16 20:33 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +struct TestMessage : public CRMessage<TestMessage<T>> {
你这里明明都是固定类型（size_t），没必要用模板

2022-12-16 20:33 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    std::this_thread::sleep_for(std::chrono::milliseconds(100));
你等的其实是snapshot都完成？那你是不是应该显式地写出来，而不是照抄其他的注释？而且这样的话等100ms没啥道理吧，不应该是一直取snapshot看数量是不是有那么多个？

2022-12-16 20:33 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +                    (previous_value->load() <= expect_value + kFlakyIgnoreNum));
不要load这么多次。一开始就取好然后后面直接用那个值，不然直接load如果这个值继续在变那你有bug也很难调

2022-12-16 20:33 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +            std::chrono::duration_cast<std::chrono::seconds>(kMessageNum * kSleepBetweenMessages).count();
- 算秒数只是总时间，你还要除周期才是snapshot数（虽然现在周期是1，但这只是碰巧对，如果以后测试想换周期呢？）
- 提前算好，给一个易读的名字（`kExpectedSnapshotNum`?）

2022-12-16 20:33 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    static constexpr double          kSpeedUpFactor        = 1e9;
- 这两个不是全局的配置，而只是用于检查snapshot是否正确，那你可以放在更小的scope里
- 解释一下这些是什么意思，为什么是这个值

2022-12-19 03:19 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +    static constexpr double          kSpeedUpFactor        = 1e9;
要不我speed up factor也不存一个变量了，直接填进`SetSpeedUpRate`里面吧，函数名字其实很直观了

2022-12-19 05:21 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +            std::chrono::duration_cast<std::chrono::seconds>(kMessageNum * kSleepBetweenMessages).count();
那我周期还是存一个变量吧，毕竟之后UT可能会改，牺牲一点点`IntervalConfig`的可读性

2022-12-19 06:36 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +        std::unique_lock lock(snapshot_mtx_);
修改了
遵照的规则是：需要跟CV配合的 统一用`unique_lock`和`lock`变量；只需要scope功能的锁统一用`lock_guard`和`lck`变量

2022-12-20 00:12 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    std::map<std::string, std::vector<std::filesystem::path>> snapshot_path_map = recorder.GetSnapshotPaths();
这时候snapshot一定做完了吗？

2022-12-20 00:12 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    const std::size_t kFlakyIgnoreNum = 1;
为什么忽略两边会有flexibility？为什么你的测试不是确定性结果？是不是你写错了？

我知道这里应该没错，但我觉得其他任何人看到你这个都会有疑问。所以你最好解释清楚你为什么会需要这个东西（xxx tolerance是不是比“flaky ignore num”更清楚一点？）

2022-12-20 00:12 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +            replayer.SetSpeedupRate(1e9);
解释一下为什么是1e9。

> 要不我speed up factor也不存一个变量了，直接填进SetSpeedUpRate里面吧，函数名字其实很直观了

直观的部分是你给加速了1e9，不直观的是为什么是1e9，有什么意义吗还是随便选的，随便选为什么是1e9不是1，不是1e-9

2022-12-20 00:12 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +        const std::size_t kTotalTimeSec =
duration可以直接除，没必要转成整数。直接用duration也不需要名字里带单位

2022-12-20 23:22 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    for (std::size_t i = 1; i <= kMessageNum; ++i) {
nit: 我们一般都是写0开始，然后用`< kMessageNum`。这样不仅短一个字符，而且很多时候0开始的index更方便处理

2022-12-20 23:41 UTC, chenhao94 approved these changes

2022-12-20 23:41 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    std::map<std::string, std::vector<std::filesystem::path>> snapshot_path_map = recorder.GetSnapshotPaths();
理想情况是这样，但还是之前说的，调度经常是很糙的，各种时间点通常不像你想得那么精确。所以为了让测试更robust，你这里可以预先检查取出来的snapshot是不是够多，如果少了，可以允许多等一会儿（比如100ms取一次，取到数量够了或者超过一定时间（比如半个周期）为止）

2022-12-26 03:14 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +    for (std::size_t i = 1; i <= kMessageNum; ++i) {
我原来想的是从1开始的话可以在下面直接判断 (因为毕竟previous_size_t 是 size_t 从0开始)
```
EXPECT_EQ(message->value_ - previous_size_t->load(), 1);
```
这样就不用额外判断一行，如果是0就跳过这行之类的

2022-12-26 06:15 UTC, merged