Add max snapshot number option to the recorder config
cyfitech/cris-core pull request #127
Opened 2022-12-20 06:23 UTC by YuzhouGuo

Associate with the feature
- https://github.com/cyfitech/cris-core/issues/97

Feature description:
Let the user specify the max number of snapshots to be kept locally.

2022-12-20 23:46 UTC, chenhao94 commented on src/config/recorder_config.h
> +        std::size_t          max_copy_;
给个default？

2022-12-20 23:46 UTC, chenhao94 commented on src/config/recorder_config.cc
> +            Fail("\"interval_max_copy\" is required.", ec);
为啥这个要required？规定默认行为就好了

2022-12-20 23:46 UTC, chenhao94 commented on tests/config_test.cc
> +                            "interval_max_copy": 5
才发现你这里，5秒叫secondly，1秒叫hourly，是不是有点奇怪啊？对于测试，这确实没错，但测试代码同时也有样例的作用，这个样例有点迷惑吧

2022-12-26 02:03 UTC, YuzhouGuo commented on tests/config_test.cc
> +                            "interval_max_copy": 5
我起个SECONDLY_EXAMPLE_1之类的好了

2022-12-26 02:03 UTC, YuzhouGuo commented on src/config/recorder_config.h
> +        std::size_t          max_copy_;
那就暂定48咯？

2023-01-04 02:11 UTC, chenhao94 commented on src/config/recorder_config.h
> +        static constexpr std::size_t kDefaultMaxNumOfCopies = 48;
static成员放到后面，空行隔开

2023-01-04 02:11 UTC, chenhao94 commented on src/config/recorder_config.cc
> +        std::size_t max_num_of_copies = 0;
uint64，simdjson不支持size_t，你这里能过只是因为你的系统里这两者**碰巧**一样。其他系统里这不一定。你需要用uint64_t解析，完了以后static cast成size_t

2023-01-04 02:11 UTC, chenhao94 commented on src/config/recorder_config.cc
> +                Fail("Expect a number for \"max_num_of_copies\".", ec);
"max_num_of_copies" must be an unsigned integer.

2023-01-05 03:04 UTC, chenhao94 requested changes

2023-01-05 03:41 UTC, YuzhouGuo commented on src/config/recorder_config.cc
> +        if (max_num_of_copies != 0) {
这边的目的其实只是不想让用户的输入覆盖 default，那我默认-1可以吗，-1绝对是invalid input了

2023-01-05 03:51 UTC, chenhao94 commented on src/config/recorder_config.cc
> +        if (max_num_of_copies != 0) {
无符号哪来的-1。你解析的时候知道有没有值，或者说你直接先初始化成默认值也可以

2023-01-06 02:25 UTC, chenhao94 approved these changes

2023-01-06 02:39 UTC, merged