Recorder snapshot feature with user-specified max copy number
cyfitech/cris-core pull request #129
Opened 2022-12-26 11:06 UTC by YuzhouGuo

Associate with the feature
- https://github.com/cyfitech/cris-core/issues/97

Depends on the PR
- https://github.com/cyfitech/cris-core/pull/127

Feature description:
Implementation of the user-specified snapshot number to be stored locally.

2022-12-28 01:25 UTC, chenhao94 reviewed
似乎不用依赖 #125 ？

2022-12-28 01:25 UTC, chenhao94 commented on src/config/recorder_config.h
> +        std::size_t          max_copy_{48};
为什么是48

2022-12-28 01:25 UTC, chenhao94 commented on src/config/recorder_config.cc
> +        if (const auto ec = data["interval_max_copy"].get(interval_max_copy)) {
“interval”这个前缀是不是没什么用，这都已经是interval配置内部的东西了

2022-12-28 01:25 UTC, chenhao94 commented on src/config/recorder_config.cc
> +        if (interval_max_copy != 0) {
=0不可以吗？就是不保留任何snapshot的意思？

2022-12-28 01:25 UTC, chenhao94 commented on src/config/recorder_config.cc
> +        if (const auto ec = data["interval_max_copy"].get(interval_max_copy)) {
```
{
   "name": 
   "period_sec": 
   "max_num_of_copies": 
}
```
?

2022-12-28 02:14 UTC, YuzhouGuo commented on src/config/recorder_config.cc
> +        if (interval_max_copy != 0) {
当前状况下`interval_max_copy==0`的意思是client并没有配置，那应该使用intervalConfig默认的数量，如果这边initialize的时候不判断0一起设置掉的话就直接覆盖了（这部分修改其实是[#127](https://github.com/cyfitech/cris-core/pull/127)，到时候我会在那边改）

2022-12-28 02:15 UTC, YuzhouGuo commented on src/config/recorder_config.h
> +        std::size_t          max_copy_{48};
当时跟@xkszltl讨论的时候似乎提过这个数字，你推荐多少呢？

2022-12-28 02:20 UTC, YuzhouGuo commented
> 似乎不用依赖 #125 ？

我觉得好像依赖了recorder.cc里面的一些逻辑，计算下次醒来的时间也准备了下次generateSnapshot需要copy to的各个路径，这个时候可以顺便把config里面的max copy num拿出来比较。其实不依赖也可以，只是multi interval做完之后可能再改。

2022-12-28 02:59 UTC, chenhao94 commented on src/config/recorder_config.h
> +        std::size_t          max_copy_{48};
是几都没问题，问题是你需要定义常量，并解释，而不要一个谁都不知道怎么来的magic number放在这

2022-12-29 19:28 UTC, chenhao94 commented on src/config/recorder_config.h
>          std::chrono::seconds interval_sec_;
period?
- interval是多余的信息
- sec也是，类型里已经带过单位了

2022-12-29 19:28 UTC, chenhao94 commented on src/config/recorder_config.h
> +// Save 48 snapshots locally for each time interval as default
你的变量名差不多表达了同样的意思，所以不用写。另外你在这里重复了“48”这个数，这样不太好，因为以后有修改的话容易造成不一致。所以注释只说作用，不用说是多少。

2022-12-29 19:28 UTC, chenhao94 commented on src/config/recorder_config.h
> +constexpr std::size_t kDefaultMaxCopyNum = 48;
定义成IntervalConfig的静态成员

2022-12-29 19:28 UTC, chenhao94 commented on src/config/recorder_config.h
> +        std::size_t          max_copy_{kDefaultMaxCopyNum};
max_num_of_copies, kDefaultMaxNumOfCopies.

2022-12-29 19:28 UTC, chenhao94 commented on tests/config_test.cc
> +                            "name": "SECONDLY_EX_1",
EX_1是什么？直接说"5s"或者"5 seconds"是不是就可以了

2022-12-29 19:28 UTC, chenhao94 commented on tests/config_test.cc
> +                            "name": "SECONDLY",
明明是5秒，为什么要说是secondly？

2023-01-05 19:49 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    auto now = std::chrono::system_clock::now();
now不是个合适的变量名，这一刻之后它就不是now

2023-01-05 19:50 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    auto sse = now.time_since_epoch();
sse是什么？感觉并不是一个好认出的缩写

2023-01-05 19:52 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    auto now = std::chrono::system_clock::now();
好好检查一下整个文件，这上面lock_guard，error_code，for_each，vector，move都没有include

2023-01-06 02:23 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +    auto now = std::chrono::system_clock::now();
嗯嗯稍等啊，我等dependency PR通过之后，在[这个PR](https://github.com/cyfitech/cris-core/pull/125)统一修改

2023-02-05 04:58 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +TEST_F(RecorderSnapshotTest, RecorderSnapshotMaxCopyNumTest) {
你这个测试在测什么？如果只是看snapshot数目是不是正确的话，应该很简单吧？为什么感觉你还是复制粘贴了一个上面一样的东西？我也不知道你在哪里检查了max num

2023-02-13 09:49 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +TEST_F(RecorderSnapshotTest, RecorderSnapshotMaxCopyNumTest) {
改了检查方式，也改成了4秒检验2个snapshot

2023-02-14 19:23 UTC, chenhao94 requested changes

2023-02-14 19:23 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +                    .max_num_of_copies_ = 2,
- 这个常量你要重复使用，定义到外面去
- 你定义测试时间的时候要比这里大，所以这两个东西要定义到一起

2023-02-14 19:23 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    while (snapshot_path_map["SECONDLY"].size() < kExpectedMinNum && check_num_time < check_stop_time) {
你这是要干啥，你max copy是2，可是你要等到有四个snapshot？不觉得不对吗？

2023-02-14 19:23 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    EXPECT_EQ(snapshot_path_map["SECONDLY"].size(), 2);
- 不光是最后，中间任何时候数量都不可以超（或者中间也有可能有一瞬间超过1个？但超很多是不可以的）
- 不要光看这个list，也要看是不是真的已经删掉了，这里你可以简单地用std::filesystem的函数查一下数量。要稍微filter一下，避免其他手动加入的临时文件影响计数（比如看看是不是directory，简单检查一下内部结构看看是不是snaposhot之类的）
- 不光是数量，也要检查留下来的是不是最新的snapshot

2023-02-20 09:21 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +    EXPECT_EQ(snapshot_path_map["SECONDLY"].size(), 2);
@chenhao94 起了一个子线程全程判断snapshot数量（因为是for循环的有限逻辑所以就detach了）

2023-02-21 05:19 UTC, chenhao94 requested changes

2023-02-21 05:19 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +        if (i == 10) {
why 10？一开始就做不可以吗？如果你需要snapshot位置之类的信息，你大可以直接让recorder给你。你控制着所有实现，没必要从外面hack一个路径出来吧？

2023-02-21 05:19 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +            consumer.detach();
假如有任何原因让这个子线程调度到很晚才结束，那你会访问已经被清空的临时目录，甚至是早已析构的log infra。所以强烈不推荐detach，除非你很确定自己在干什么

2023-02-21 05:19 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +                for (std::size_t j = 10; j < kMessageNum; ++j) {
这个j没什么用，难道你循环同样次数就会和外面线程的循环一起结束吗？要不要回想一下学校里的操作系统和并行计算的课程，存在这样的东西吗？

你如果要让它不断检测到测试结束，那你就在测试结束时自己通知它停止，而不是祈祷操作系统按你希望的方式调度线程，因为操作系统不会管这些

2023-02-21 05:19 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    EXPECT_EQ(snapshot_path_map["SECONDLY"].size(), 2);
一样需要扫一遍文件目录，而不光是看recorder告诉你什么

2023-02-21 05:19 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +                            // Check that the folder content is in valid leveldb storage format.
我记得leveldb不是接口里的东西，只是实现细节而已吧

2023-02-21 05:19 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +                            // Check that the folder content is in valid leveldb storage format.
folder -> directory

2023-02-21 05:19 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +                            // Check that the folder content is in valid leveldb storage format.
我觉得你检查的时候可以这样：

- 先读目录下的文件列表
- 删掉recorder告诉你的snapshot
- 对于剩下的东西，你再去检查格式

2023-02-21 05:19 UTC, chenhao94 commented on tests/recorder_snapshot_test.cc
> +    // Check that the only 'kMaxNumOfCopies' snapshots kept matches the last element value in each interval.
有没有什么可以直接读到最后一个元素的接口？没有的话你可以另写一个函数，或者考虑能不能提供类似接口（专给测试用也是可以的）。这些subscirbe和replay什么的混在一起会干扰你的测试逻辑，导致没有那么可读。你的测试逻辑本身是很简单的，只是看看最后一个元素来判断这个snapshot够不够新而已。如果有更简便的判断方式也没问题

2023-02-21 09:27 UTC, YuzhouGuo commented on tests/recorder_snapshot_test.cc
> +    // Check that the only 'kMaxNumOfCopies' snapshots kept matches the last element value in each interval.
嗯我写一个这样的测试接口吧，这样snapshot test也可以用

2024-01-25 02:25 UTC, xkszltl commented
Close stale PR.

2024-01-25 02:25 UTC, closed without merging