Fix snapshot test data race issue
cyfitech/cris-core pull request #134
Opened 2023-01-03 08:53 UTC by YuzhouGuo

Associate with the issue:
- https://github.com/cyfitech/cris-core/issues/132

2023-01-03 10:32 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    std::vector<WakeUpConfig> snapshot_wakeup_intervals;
include

2023-01-03 10:33 UTC, xkszltl commented on tests/recorder_snapshot_test.cc
> +    void TestSnapshot(RecorderConfig recorder_config);
const &?

2023-01-03 10:34 UTC, xkszltl commented on tests/recorder_snapshot_test.cc
> +    const std::size_t kExpectedMinNum = kMessageNum * kSleepBetweenMessages / std::chrono::milliseconds(1) + 1;
include cstddef

2023-01-03 10:34 UTC, xkszltl commented on tests/recorder_snapshot_test.cc
> +                std::lock_guard   lck(mtx);
include

2023-01-03 10:35 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +            std::chrono::duration_cast<std::chrono::milliseconds>(next_snapshot_wakeup.interval_config.interval_sec_) *
include

2023-01-03 10:35 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +        [](const WakeUpConfig l, const WakeUpConfig r) { return l.wake_time > r.wake_time; });
Should it be const ref?

2023-01-03 10:36 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +        snapshot_cv_.wait_until(lck, next_snapshot_wakeup.wake_time, [this] { return snapshot_shutdown_flag_.load(); });
Should we capture just the snapshot_shutdown_flag_ itself? by ref

2023-01-03 10:37 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +        snapshot_cv_.wait_until(lck, next_snapshot_wakeup.wake_time, [this] { return snapshot_shutdown_flag_.load(); });
Given there's only one var used

2023-01-03 10:41 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +        snapshot_cv_.wait_until(lck, next_snapshot_wakeup.wake_time, [this] { return snapshot_shutdown_flag_.load(); });
不太行，`error: 'snapshot_shutdown_flag_' in capture list does not name a variable`

2023-01-03 10:52 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +#include <ratio>
I don't think you're using ratio directly anywhere.
include chrono

2023-01-03 10:53 UTC, xkszltl commented on tests/recorder_snapshot_test.cc
> +#include <ratio>
ratio is only required when using ratio directly, e.g. milli.
milliseconds is defined by chrono using ratio, but not in ratio.

2023-01-04 02:04 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +#include <ratio>
好的我本地修改下，这个PR的rebase有问题我之后提一个新的

2023-01-04 02:04 UTC, closed without merging

2023-01-04 02:05 UTC, chenhao94 requested changes
bugfix请单独做，不要和多周期混在一起。对于bug我们永远希望尽快unblock，而不是去等其他的功能

2023-01-04 02:05 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +        if ((next_snapshot_wakeup.wake_time - std::chrono::steady_clock::now()) > kSkipThreshold) {
几个增加可读性的建议
- next_xxx -> current_xxx, 因为在循环的主要逻辑里，这个是当前snapshot的时间
- 最开始定义一个`next_wake_time_for_this_interval`，而不是直接叫next，因为这并不一定是下一次醒来的时间
- waketime更新挨着放到push之前，这样能清楚地表达出“处理结束，下次醒来是xxx”这个信息

2023-01-04 06:44 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +    next_snapshot_ = next_snapshot_wakeup.interval_config;
这个下面的GenerateSnapshotImpl会用，不过改成传参数也行

2023-01-04 06:58 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    next_snapshot_ = next_snapshot_wakeup.interval_config;
不必要的局部状态不要存到成员里，这和避免全局变量是一个道理。状态尽量少不仅是让类少一个变量，更重要的是这样更不容易有不必要的副作用

2023-01-04 10:06 UTC, YuzhouGuo commented on src/msg_recorder/recorder.cc
> +        if ((next_snapshot_wakeup.wake_time - std::chrono::steady_clock::now()) > kSkipThreshold) {
我写的这个跟上次的伪代码不完全一样，因为一开始需要抓取0秒 data 所以是先generate再sleep的，跟伪代码的逻辑相当于错开一位（所以要先push，queue自动排列之后取出最上层的interval，然后根据这个interval算好的时间sleep，最后醒来更新wake time才对）

2023-01-04 10:13 UTC, YuzhouGuo commented
https://github.com/cyfitech/cris-core/pull/125 修改提交在这个PR里面了