Add hostname
cyfitech/cris-core pull request #161
Opened 2023-02-22 10:31 UTC by zptan

[数据收集](https://github.com/cyfitech/cris/wiki/Market-data-collection#%E6%96%87%E4%BB%B6%E5%90%8D)，文件名中要包含机器名

2023-02-22 18:05 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    throw std::runtime_error{"Fail to get hostname."};
Nothrow but use empty string/optional?

2023-02-22 18:05 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    throw std::runtime_error{"Fail to get hostname."};
Or default to "unknown" if you just want to put it to the filename.

2023-02-22 18:17 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    char buf[HOST_NAME_MAX + 1];
Use string for this and substr when returning.

2023-02-22 18:18 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +#include <climits>
what is this for?

2023-02-22 18:23 UTC, xkszltl commented
And it may not be path-safe either.

2023-02-22 18:44 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    char buf[HOST_NAME_MAX + 1];
这东西是Linux特有的？是不是需要头文件？

2023-02-23 04:30 UTC, chenhao94 commented on src/msg_recorder/recorder.cc
> +    throw std::runtime_error{"Fail to get hostname."};
这肯定是不可以的。注意这里是core，你要把它当做一个基础库，行为不能过于fit某一项具体业务。hostname对于record这一项功能显然不是必须的。你检查不到可以给fallback，但直接挂掉肯定是不行的。

2023-02-23 14:42 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    char buf[HOST_NAME_MAX + 1];
> 换言之，写入后string.size()还是0

没reserve之前是没地方写的。

> 一个临时buffer何必呢，直接在stack上弄不更好？

2023-02-23 14:48 UTC, xkszltl commented
> 只要保证一个交易所机房的几台机器不重名就可以了

这个不太好保证吧？
对于生产环境，要怎么手工配才能保证这点？也许需要什么命名规则？
对于测试环境，比如CI或者docker，也有可能满足不了这个条件。

2023-02-23 14:49 UTC, xkszltl commented
我这里只是提一下潜在的问题，不是说hostname这个方案一定不行，我手上也没答案，需要你来判断该怎么应对这些问题

2023-02-23 15:06 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    char buf[HOST_NAME_MAX + 1];
> HOST_NAME_MAX在我的系统里是64

这是implementation details，也许换个地方就变成了8MB呢？
如果这不是hot path，没到要做那种程度的性能优化的地步，何必冒这个险。
如果到了那种程度，拿static thread_local cache一下结果就行了，还更快。

2023-02-23 15:14 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    char buf[HOST_NAME_MAX + 1];
拿就更应该用string了，几乎没有性能开销。
不确定长度的buf都尽量别往栈上开，栈就那么一点点空间。

2023-02-23 16:02 UTC, xkszltl commented on src/msg_recorder/recorder.cc
> +    char buf[HOST_NAME_MAX + 1];
- 为什么确定？
- 这种limit一般都是configurable的，比如在编译kernel的时候，光是看某个installation是64只能作为参考

2023-02-23 20:26 UTC, chenhao94 requested changes
我觉得如果只是数据收集时要区分机器，倒不如直接在收集的地方自动配置record dirname，不必让recorder生成

2023-02-23 20:31 UTC, chenhao94 commented
例如

https://github.com/cyfitech/cris-core/blob/5d80c80e8f569b85a17a2c80629379e694cd7bf3/tests/recorder_config_test.cc#L44-L48

写一个脚本自动生成一个这种配置不是简单多了么

2023-02-24 03:08 UTC, chenhao94 commented
在部署时可以手动做（其实估计也是一个脚本），但那时你可以对环境做很具体的假设。这里是基础库，你做不了这样的假设。

2023-02-24 04:53 UTC, chenhao94 commented
你其实不用加啊，用的时候决定如何配置路径不是够了吗

2023-02-24 05:09 UTC, chenhao94 commented
比如说你需要record是以hostname开头，那你配置模板里面写`record_dir = "%HOSTNAME_PLACEHOLDER%_xxx_my_record"`，然后每次用sed把%那串替换掉就好了

2023-02-24 06:15 UTC, closed without merging

2023-02-24 11:47 UTC, xkszltl commented
> 比如说你需要record是以hostname开头，那你配置模板里面写`record_dir = "%HOSTNAME_PLACEHOLDER%_xxx_my_record"`，然后每次用sed把%那串替换掉就好了

语法上建议用现成的，比如fmtlib或者sprintf的，不要自己弄

2023-02-24 11:48 UTC, xkszltl commented
如果是在shell层面做，也可以直接用环境变量之类的语法给过去