Temporary disable -Wconversion for glog
cyfitech/cris-core pull request #19
Opened 2022-03-04 11:32 UTC by zhouxindong

2022-03-04 16:54 UTC, chenhao94 requested changes
这么做没用，如果我要用其他头文件，或者glog本身的cc里面（而不是头文件）导致了警告，照样还是有问题。应该去给glog的build rule打补丁。

2022-03-04 16:57 UTC, xkszltl commented on includes/cris_glog.h
> +#pragma CRIS_COMPILER diagnostic push
这什么东西。。。。我觉得你没搞懂

2022-03-04 16:58 UTC, xkszltl commented on includes/cris_glog.h
> +#pragma CRIS_COMPILER diagnostic push
不是每个编译器都有这种diagnostic的，所以你需要在这里if编译器，每个分别做，不认识的就不做。而不是说遇到不认识的编译器就炸掉

2022-03-04 17:03 UTC, xkszltl commented
1. 这个可以做成通用的logging工具，以#include "cris/logging.h"的方式用，而不止是针对glog
2. raw_logging.h和stl_logging.h应该也要带上

2022-03-04 17:15 UTC, xkszltl commented on includes/cris_glog.h
> +#pragma CRIS_COMPILER diagnostic push
像gcc/clang这种情况，你直接一个if defined() || defined()包起来就好了

2022-03-05 01:20 UTC, zhouxindong commented on includes/cris_glog.h
> +#pragma CRIS_COMPILER diagnostic push
我一开始也是用的if defined()，后来发现clang和GCC的pragma语法基本上一样，除了"clang"和"GCC"本身，就把它们合并在一起。好的，我看一下

2022-03-05 11:41 UTC, xkszltl commented on includes/glog/logging.h
> +#include "ignored_conversion_logging.h"
full path

2022-03-05 11:41 UTC, xkszltl commented on includes/glog/raw_logging.h
> +#include "ignored_conversion_logging.h"
full path

2022-03-05 11:42 UTC, xkszltl commented on includes/glog/stl_logging.h
> +#include "ignored_conversion_logging.h"
full path

2022-03-05 11:42 UTC, xkszltl commented on includes/glog/ignored_conversion_logging.h
> +#include <glog/logging.h>
我觉得完全没必要区分，一次全带上就好了

2022-03-05 11:44 UTC, xkszltl commented on includes/glog/ignored_conversion_logging.h
> +#if defined(__clang__)
你搞得太复杂了

```
#if defined() || defined()
#pragma ... push
#pragma .. ignored ...
#endif

#include ...
#include ...
...

#if defined() || defined()
#pragma ... pop
#endif
```

2022-03-05 11:45 UTC, xkszltl commented on includes/glog/ignored_conversion_logging.h
> +#pragma clang diagnostic push
这个地方clang是能支持#pragma GCC的，可以不去特意做区分（当然，做也可以，但别搞这么乱）

2022-03-05 12:18 UTC, zhouxindong commented on includes/glog/ignored_conversion_logging.h
> +#include <glog/logging.h>
也行，这样简单一些

2022-03-05 12:22 UTC, zhouxindong commented on includes/glog/ignored_conversion_logging.h
> +#if defined(__clang__)
我不太清楚clang和gcc在预处理器上的差别，怕以后麻烦

2022-03-05 12:23 UTC, zhouxindong commented on includes/glog/ignored_conversion_logging.h
> +#pragma clang diagnostic push
也就是说只用 #pragma GCC就可以了？

2022-03-05 12:32 UTC, xkszltl commented on includes/glog/ignored_conversion_logging.h
> +#pragma clang diagnostic push
是啊，我昨天发的连接你看了吗

2022-03-05 12:32 UTC, xkszltl commented on includes/glog/ignored_conversion_logging.h
> +#pragma clang diagnostic push
llvm那个

2022-03-05 12:35 UTC, xkszltl commented on includes/glog/ignored_conversion_logging.h
> +#pragma once
就简简单单搞搞我们自己的logging lib，最后用的时候应该是`#include "cris/logging.h"`这样，既不应该有glog在路径里，ignore conversion这种细节用户也不关心

2022-03-05 13:29 UTC, zhouxindong commented on includes/glog/ignored_conversion_logging.h
> +#pragma once
好的

2022-03-05 13:34 UTC, xkszltl approved these changes

2022-03-06 04:39 UTC, chenhao94 approved these changes

2022-03-06 04:39 UTC, merged